#!/bin/bash
#
# 项目路径环境。所有路径默认从当前脚本所在仓库推导，迁移目录时只需保持
# rabbitbot 仓库、models、vln、pyorbbecsdk-v2-py310 位于同一项目根目录下。

RABBITBOT_PATH_ENV_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RABBITBOT_PATH_ENV_REPO_DIR="$(cd "${RABBITBOT_PATH_ENV_SCRIPT_DIR}/.." && pwd)"
RABBITBOT_PATH_ENV_PROJECTS_DIR="$(cd "${RABBITBOT_PATH_ENV_REPO_DIR}/.." && pwd)"

export RABBITBOT_REPO_DIR="${RABBITBOT_REPO_DIR:-${RABBITBOT_PATH_ENV_REPO_DIR}}"
export RABBITBOT_PROJECTS_DIR="${RABBITBOT_PROJECTS_DIR:-${RABBITBOT_PATH_ENV_PROJECTS_DIR}}"
export RABBITBOT_MODELS_DIR="${RABBITBOT_MODELS_DIR:-${RABBITBOT_PROJECTS_DIR}/models}"
export RABBITBOT_VLN_WS_DIR="${RABBITBOT_VLN_WS_DIR:-${RABBITBOT_PROJECTS_DIR}/vln/ros2_ws}"
export RABBITBOT_PYORBBEC_DIR="${RABBITBOT_PYORBBEC_DIR:-${RABBITBOT_PROJECTS_DIR}/pyorbbecsdk-v2-py310}"
export RABBITBOT_PYORBBEC_LEGACY_DIR="${RABBITBOT_PYORBBEC_LEGACY_DIR:-${RABBITBOT_PROJECTS_DIR}/pyorbbecsdk}"
export RABBITBOT_YOLO_DIR="${RABBITBOT_YOLO_DIR:-${RABBITBOT_PROJECTS_DIR}/yolo-detect}"
